languageCode = "en"
languageName = "English"
weight = 1

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/poolp_org.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  copyright = "Copyright &copy; Gilles Chehade - poolp.org"
