baseURL = "https://poolp.org"
languageCode = "en-us"
title = "poolp.org"
theme = "poolp.org_theme"
pygmentsCodeFences = true
pygmentsUseClasses = true
publishDir = "docs"
copyright = "Gilles Chehade - All rights reserved"
enableEmoji = true

[markup.goldmark.renderer]
  unsafe = true

[Params]
	mainSections = ["posts"]
	logo = "/images/poolp_org.png"
	commit = false
	rss = true
	comments = false
	readingTime = true
	wordCount = true
	useHLJS = true
	socialShare = true
	showRelatedPosts = true

[Params.author]
  name = "Gilles Chehade"
  thumbnail = "/images/me.jpg"
  description = ""
  website = "https://poolp.org"
  email = "gilles@poolp.org"
  facebook = "gilles.chehade"
  github = "poolpOrg"
  twitter = "poolpOrg"
  reddit = "poolpOrg"
  linkedin = "gilleschehade"
  paypal = "poolpOrg"

[Params.index]
  picture = "/images/me.jpg"
  title = "Gilles Chehade"
  subtitle = "foobarbazing since 1981"
  mdtext = '''
Currently trying to get this blog running,\
**Be patient.**
### This is a markdown heading
'''
  alertbar = false

[Params.social]
  github = "poolpOrg"
  linkedin = "gilleschehade"
  twitter = "poolpOrg"


[Author]
	name = "Gilles Chehade"
	website = "https://poolp.org"
	email = "gilles@poolp.org"
    facebook = "gilles.chehade"
	github = "poolpOrg"
	twitter = "poolpOrg"
	reddit = "poolpOrg"
	linkedin = "gilles.chehade"
	paypal = "poolpOrg"

[permalinks]
	posts = "/posts/:year-:month-:day/:slug"

[outputs]
	home = ["HTML", "RSS"]
	section = ["HTML", "RSS"]
	page = ["HTML"]

[[menu.main]]
    name = "Articles"
    url = "/posts"
    weight = 1

[[menu.main]]
    name = "Freelance"
    url = "/fr/contracting/"
    weight = 2

[[menu.main]]
    name = "Hypnose"
    url = "https://hypno.cat"
    weight = 5
