baseURL = "https://poolp.org"
languageCode = "en-us"
title = "poolp.org"
theme = "poolp.org_theme"
pygmentsCodeFences = true
pygmentsUseClasses = true
publishDir = "docs"
copyright = "poolp.org - All rights reserved"
enableEmoji = true

[markup.goldmark.renderer]
  unsafe = true

[Params]
	mainSections = ["posts"]
	logo = "/images/poolp_org.png"
	commit = false
	rss = true
  ShowFullTextinRSS = true
	comments = false
	readingTime = true
	wordCount = true
	useHLJS = true
	socialShare = true
	showRelatedPosts = true
  alertbar = true

[Params.author]
  name = "Gilles Chehade"
  thumbnail = "/images/me.jpg"
  description = ""
  website = "https://poolp.org"
  email = "gilles@poolp.org"
  facebook = "gilles.chehade"
  github = "poolpOrg"
  twitter = "poolpOrg"
  reddit = "poolpOrg"
  linkedin = "gilleschehade"
  paypal = "poolpOrg"

[permalinks]
	posts = "/posts/:year-:month-:day/:slug"

[outputs]
	home = ["HTML", "RSS"]
	section = ["HTML", "RSS"]
	page = ["HTML"]

[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"
