baseURL = "https://poolp.org"
languageCode = "en-us"
title = "poolp.org"
#theme = "mediumish-gohugo-theme"
theme = "digitalgarden"
#pygmentsCodeFences = true
#pygmentsUseClasses = true
publishDir = "docs"
copyright = "poolp.org - All rights reserved"
enableEmoji = true

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    style = "dracula"
  

[Params]
	mainSections = ["posts"]
	logo = "/images/poolp_org.png"
	commit = false
	rss = true
  ShowFullTextinRSS = true
	comments = true
	readingTime = true
	socialShare = true
	showRelatedPosts = true
  alertbar = true
  description = "My Digital Garden on the Internet"
  images = ['/images/poolp_org.png']
  enableSearch = true
  useHLJS = true

[Params.author]
  name = "Gilles Chehade"
  thumbnail = "/images/me.jpg"
  description = ""
  website = "https://poolp.org"
  email = "gilles@poolp.org"
  facebook = "gilles.chehade"
  github = "poolpOrg"
  twitter = "poolpOrg"
  reddit = "poolpOrg"
  linkedin = "gilleschehade"
  paypal = "poolpOrg"

[permalinks]
	posts = "/posts/:year-:month-:day/:slug"

[outputs]
	home = ["HTML", "RSS"]
	section = ["HTML", "RSS"]
	page = ["HTML"]

[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"

[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1
[[menu.main]]
  name = 'Technology'
  params.header = true
  weight = 2
[[menu.main]]
  name = 'Articles'
  url = '/posts'
  weight = 3
[[menu.main]]
  name = 'Stack'
  url = '/stack'
  weight = 5


#[[menu.main]]
#  name = 'Links'
#  params.header = true
#  weight = 6
#[[menu.main]]
#  name = 'OpenBSD'
#  url = 'https://OpenBSD.org'
#  weight = 7




[[menu.social]]
  name = 'Twitter'
  url = 'https://twitter.com/poolpOrg'
  weight = 1

[[menu.social]]
  name = 'GitHub'
  url = 'https://github.com/poolpOrg'
  weight = 2

[[menu.social]]
  name = 'LinkedIn'
  url = 'https://linkedin.com/in/gilleschehade'
  weight = 3

[[menu.social]]
  name = 'Email'
  url = 'mailto:gilles@poolp.org'
  weight = 4

[[menu.social]]
  name = 'RSS'
  url = '/index.xml'
  weight = 4
