baseURL = "https://poolp.org"
languageCode = "en-us"
title = "poolp.org"
theme = "digitalgarden"
publishDir = "docs"
copyright = "poolp.org - All rights reserved"
enableEmoji = true

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    style = "dracula"

[Params]
  description = "My Digital Garden on the Internet"
  images = ['/images/poolp_org.png']
  enableSearch = true

[outputs]
	home = ["HTML", "RSS"]
	section = ["HTML", "RSS"]
	page = ["HTML", "RSS"]

[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"

[permalinks]
  posts = "/posts/:year-:month-:day/:slug"

[menu]
[[menu.main]]
  identifier = "personal"
  name = 'Personal'
  params.header = true
  weight = 1
[[menu.main]]
  identifier = "personal-articles"
  name = 'articles'
  url = '/categories/personal'
  weight = 2

[[menu.main]]
  identifier = "home"
  name = 'Home'
  url = '/'
  weight = 1
[[menu.main]]
  identifier = "technology"
  name = 'Technology'
  params.header = true
  weight = 2
[[menu.main]]
  identifier = "technology-articles"
  name = 'articles'
  url = '/categories/technology'
  weight = 3
[[menu.main]]
  identifier = "technology-books"
  name = 'books'
  url = '/books/technology'
  weight = 4
#[[menu.main]]
#  name = 'tech projects'
#  url = '/tech/projects'
#  weight = 4
[[menu.main]]
  identifier = "technology-stack"
  name = 'stack'
  url = '/stack/technology'
  weight = 5

[[menu.main]]
  identifier = "music"
  name = 'Music'
  params.header = true
  weight = 20
[[menu.main]]
  identifier = "music-articles"
  name = 'articles'
  url = '/categories/music'
  weight = 21
#[[menu.main]]
#  identifier = "music-books"
#  name = 'books'
#  url = '/books/music'
#  weight = 22
[[menu.main]]
  identifier = "music-stack"
  name = 'stack'
  url = '/stack/music'
  weight = 23


#[[menu.main]]
#  name = 'All'
#  params.header = true
#  weight = 90
#[[menu.main]]
#  name = 'all articles'
#  url = '/posts'
#  weight = 91



[[menu.main]]
  name = 'Misc.'
  params.header = true
  weight = 100
[[menu.main]]
  name = 'about me'
  url = '/about/me'
  weight = 101




[[menu.social]]
  name = 'Twitter'
  url = 'https://twitter.com/poolpOrg'
  weight = 1

[[menu.social]]
  name = 'Mastodon'
  url = 'https://social.poolp.org/@gilles'
  weight = 2

[[menu.social]]
  name = 'GitHub'
  url = 'https://github.com/poolpOrg'
  weight = 3

[[menu.social]]
  name = 'LinkedIn'
  url = 'https://linkedin.com/in/gilleschehade'
  weight = 4

[[menu.social]]
  name = 'Email'
  url = 'mailto:gilles@poolp.org'
  weight = 5

[[menu.social]]
  name = 'RSS'
  url = '/index.xml'
  weight = 6
