baseURL = "https://poolp.org/"
languageCode = "en-us"
title = "poolp.org"
theme = "poolp.org_theme"
pygmentsCodeFences = true
pygmentsUseClasses = true
publishDir = "docs"

[markup.goldmark.renderer]
    unsafe= true

[Params]
	mainSections = ["post", "posts"]
	#logo = "/images/me.jpg"
	commit = false
	rss = true
	#comments = true
	readingTime = true
	wordCount = true
	useHLJS = true
	socialShare = true
	showRelatedPosts = true

[Author]
	name = "Gilles Chehade"
	website = "https://poolp.org"
	email = "gilles@poolp.org"
    facebook = "gilles.chehade"
	github = "poolpOrg"
	twitter = "poolpOrg"
	reddit = "poolpOrg"
	linkedin = "gilles.chehade"
	paypal = "poolpOrg"

[permalinks]
	posts = "/posts/:year-:month-:day/:slug"

[outputs]
	home = ["HTML", "RSS"]
	section = ["HTML", "RSS"]
	page = ["HTML"]

[[menu.main]]
    name = "Freelance"
    url = ""
    weight = 1

[[menu.main]]
    name = "Sponsorship"
    url = "/sponsorship/"
    weight = 2

[[menu.main]]
    name = "Social"
    url = ""
    weight = 3

[[menu.main]]
    name = "Curriculum"
    url = ""
    weight = 4

[[menu.main]]
    name = "Hypnose"
    url = "https://hypno.cat"
    weight = 5


[[menu.main]]
    parent = "Freelance"
    name = "[en] Hire me !"
    url = "/en/contracting/"
    weight = 1

[[menu.main]]
    parent = "Freelance"
    name = "[fr] Recrutez moi !"
    url = "/fr/contracting/"
    weight = 2

[[menu.main]]
    parent = "Sponsorship"
    name = "[en] Sponsor me !"
    url = "/en/sponsorship/"
    weight = 1

[[menu.main]]
    parent = "Sponsorship"
    name = "[fr] Sponsorisez moi !"
    url = "/fr/sponsorship/"
    weight = 2

[[menu.main]]
    parent = "Social"
    name = "Patreon"
    url = "https://patreon.com/gilles"
    weight = 1

[[menu.main]]
    parent = "Social"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/gilleschehade"
    weight = 2

[[menu.main]]
    parent = "Social"
    name = "Github"
    url = "https://github.com/poolpOrg"
    weight = 3

[[menu.main]]
    parent = "Social"
    name = "Twitter"
    url = "https://twitter.com/poolpOrg"
    weight = 4


[[menu.main]]
    parent = "Curriculum"
    name = "EN"
    url = "https://github.com/poolpOrg/resume/blob/master/resume.en.pdf"
    weight = 1

[[menu.main]]
    parent = "Curriculum"
    name = "FR"
    url = "https://github.com/poolpOrg/resume/blob/master/resume.fr.pdf"
    weight = 2
