name: CI

on:
  push:
    branches: [ master ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Publish Site
        uses: chabad360/hugo-gh-pages@master
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to poolp.org
        run: ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_MACHINE }} "(cd ${{ secrets.SSH_DIRECTORY}} && git pull)"
